version: '3'
services:
  db:
    container_name: d3v_sm_pg
    image: postgres:latest
    restart: always
    volumes:
      - d3v_sm_pg_data:/var/lib/postgresql/data\
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - d3v_sm_network_backend
  adminer:
    links:
    - db:postgres
    container_name: d3v_sm_adminer
    restart: always
    image: adminer
    ports:
    - 7011:8080
    networks:
      - d3v_sm_network_backend
volumes:
  d3v_sm_pg_data:
networks:
  d3v_sm_network_backend: