version: '3'
services:
  db:
    container_name: d3v_sm_pg
    image: postgres:latest
    restart: always
    volumes:
      - d3v_sm_pg_data:/var/lib/postgresql/data\
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./.env
  adminer:
    links:
    - db:postgres
    container_name: d3v_sm_adminer
    restart: always
    image: adminer
    ports:
    - 7011:8080
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis


volumes:
  d3v_sm_pg_data: